-- =============================================
-- CONFIGURATION DU CONTEXTE
-- =============================================

USE DATABASE MUSIC_DWH;
USE SCHEMA STAR_SCHEMA;
USE WAREHOUSE WAREHOUSE_DST;

-- =============================================
-- SUPPRESSION DES TABLES (dans l’ordre inverse)
-- =============================================

DROP TABLE IF EXISTS FACT_PLAYLIST_TRACKS;
DROP TABLE IF EXISTS FACT_TRACKS;

DROP TABLE IF EXISTS DIM_DATE;
DROP TABLE IF EXISTS DIM_PLAYLIST;
DROP TABLE IF EXISTS DIM_ALBUM;
DROP TABLE IF EXISTS DIM_GENRE;
DROP TABLE IF EXISTS DIM_MEDIA_TYPE;
DROP TABLE IF EXISTS DIM_ARTIST;

-- =============================================
-- CRÉATION DES DIMENSIONS
-- =============================================

CREATE OR REPLACE TABLE DIM_ARTIST (
    ARTIST_ID NUMERIC PRIMARY KEY,
    ARTIST_NAME VARCHAR,
    BIRTH_YEAR NUMERIC,
    COUNTRY VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_MEDIA_TYPE (
    MEDIA_TYPE_ID NUMERIC PRIMARY KEY,
    MEDIA_TYPE_NAME VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_GENRE (
    GENRE_ID NUMERIC PRIMARY KEY,
    GENRE_NAME VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_ALBUM (
    ALBUM_ID NUMERIC PRIMARY KEY,
    ALBUM_TITLE VARCHAR,
    ARTIST_ID NUMERIC,
    PRODUCTION_YEAR NUMERIC,
    RELEASE_YEAR NUMERIC,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ARTIST_ID) REFERENCES DIM_ARTIST(ARTIST_ID)
);

CREATE OR REPLACE TABLE DIM_PLAYLIST (
    PLAYLIST_ID NUMERIC PRIMARY KEY,
    PLAYLIST_NAME VARCHAR,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE DIM_DATE (
    DATE_ID DATE PRIMARY KEY,
    DAY_NUMBER NUMERIC,
    DAY_NAME VARCHAR,
    MONTH_NUMBER NUMERIC,
    MONTH_NAME VARCHAR,
    YEAR NUMERIC,
    QUARTER NUMERIC,
    WEEK_OF_YEAR NUMERIC,
    DAY_OF_WEEK NUMERIC,
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    SEASON VARCHAR
);

-- =============================================
-- CRÉATION DES FAITS
-- =============================================

CREATE OR REPLACE TABLE FACT_TRACKS (
    TRACK_ID NUMERIC PRIMARY KEY,
    TRACK_NAME VARCHAR,
    MEDIA_TYPE_ID NUMERIC,
    GENRE_ID NUMERIC,
    ALBUM_ID NUMERIC,
    COMPOSER VARCHAR,
    DURATION_MS NUMERIC,
    SIZE_BYTES NUMERIC,
    UNIT_PRICE NUMERIC(10,2),
    RELEASE_DATE DATE,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (MEDIA_TYPE_ID) REFERENCES DIM_MEDIA_TYPE(MEDIA_TYPE_ID),
    FOREIGN KEY (GENRE_ID) REFERENCES DIM_GENRE(GENRE_ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES DIM_ALBUM(ALBUM_ID),
    FOREIGN KEY (RELEASE_DATE) REFERENCES DIM_DATE(DATE_ID)
);

CREATE OR REPLACE TABLE FACT_PLAYLIST_TRACKS (
    PLAYLIST_ID NUMERIC,
    TRACK_ID NUMERIC,
    ADDED_DATE DATE NOT NULL DEFAULT '2000-01-01'::DATE,
    LOAD_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PLAYLIST_ID, TRACK_ID, ADDED_DATE),
    FOREIGN KEY (PLAYLIST_ID) REFERENCES DIM_PLAYLIST(PLAYLIST_ID),
    FOREIGN KEY (TRACK_ID) REFERENCES FACT_TRACKS(TRACK_ID),
    FOREIGN KEY (ADDED_DATE) REFERENCES DIM_DATE(DATE_ID)
);

-- =============================================
-- INSERTION DES DONNÉES
-- =============================================

-- 1. DIM_DATE
INSERT INTO DIM_DATE (
    DATE_ID, DAY_NUMBER, DAY_NAME, MONTH_NUMBER, 
    MONTH_NAME, YEAR, QUARTER, WEEK_OF_YEAR, 
    DAY_OF_WEEK, IS_WEEKEND, IS_HOLIDAY, SEASON
)
WITH date_series AS (
    SELECT DATEADD(DAY, SEQ4(), '2000-01-01') AS date_value
    FROM TABLE(GENERATOR(ROWCOUNT => 10000))
)
SELECT
    date_value AS DATE_ID,
    DAY(date_value) AS DAY_NUMBER,
    DAYNAME(date_value) AS DAY_NAME,
    MONTH(date_value) AS MONTH_NUMBER,
    MONTHNAME(date_value) AS MONTH_NAME,
    YEAR(date_value) AS YEAR,
    QUARTER(date_value) AS QUARTER,
    WEEKOFYEAR(date_value) AS WEEK_OF_YEAR,
    DAYOFWEEK(date_value) AS DAY_OF_WEEK,
    DAYOFWEEK(date_value) IN (6, 7) AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY,
    CASE 
        WHEN MONTH(date_value) IN (12, 1, 2) THEN 'Winter'
        WHEN MONTH(date_value) IN (3, 4, 5) THEN 'Spring'
        WHEN MONTH(date_value) IN (6, 7, 8) THEN 'Summer'
        WHEN MONTH(date_value) IN (9, 10, 11) THEN 'Autumn'
    END AS SEASON
FROM date_series
WHERE date_value <= CURRENT_DATE();

-- 2. DIM_ARTIST
INSERT INTO DIM_ARTIST (ARTIST_ID, ARTIST_NAME, BIRTH_YEAR, COUNTRY)
SELECT ArtistId, Name, Birthyear, Country FROM DST_DB.PUBLIC.Artist;

-- 3. DIM_MEDIA_TYPE
INSERT INTO DIM_MEDIA_TYPE (MEDIA_TYPE_ID, MEDIA_TYPE_NAME)
SELECT MediaTypeId, Name FROM DST_DB.PUBLIC.MediaType;

-- 4. DIM_GENRE
INSERT INTO DIM_GENRE (GENRE_ID, GENRE_NAME)
SELECT GenreId, Name FROM DST_DB.PUBLIC.Genre;

-- 5. DIM_ALBUM
INSERT INTO DIM_ALBUM (ALBUM_ID, ALBUM_TITLE, ARTIST_ID, PRODUCTION_YEAR, RELEASE_YEAR)
SELECT AlbumId, Title, ArtistId, Prod_year, Cd_year FROM DST_DB.PUBLIC.Album;

-- 6. DIM_PLAYLIST
INSERT INTO DIM_PLAYLIST (PLAYLIST_ID, PLAYLIST_NAME)
SELECT PlaylistId, Name FROM DST_DB.PUBLIC.Playlist;

-- 7. FACT_TRACKS
INSERT INTO FACT_TRACKS (
    TRACK_ID, TRACK_NAME, MEDIA_TYPE_ID, GENRE_ID, 
    ALBUM_ID, COMPOSER, DURATION_MS, SIZE_BYTES, UNIT_PRICE, RELEASE_DATE
)
SELECT 
    TrackId, 
    Name, 
    MediaTypeId, 
    GenreId,
    AlbumId, 
    Composer, 
    Milliseconds, 
    Bytes, 
    UnitPrice,
    '2000-01-01'::DATE AS RELEASE_DATE
FROM DST_DB.PUBLIC.Track;

-- 8. FACT_PLAYLIST_TRACKS
INSERT INTO FACT_PLAYLIST_TRACKS (PLAYLIST_ID, TRACK_ID, ADDED_DATE)
SELECT 
    PlaylistId,
    TrackId,
    CURRENT_DATE() AS ADDED_DATE
FROM DST_DB.PUBLIC.PlaylistTrack;

-- 9. Ici, le but sera d'analyser les _tracks_ présents sur les CDs
ALTER TABLE DIM_ALBUM ADD COLUMN NUMBER_OF_TRACKS NUMERIC;


UPDATE DIM_ALBUM a
SET NUMBER_OF_TRACKS = (
    SELECT COUNT(*) 
    FROM FACT_TRACKS t 
    WHERE t.ALBUM_ID = a.ALBUM_ID
);


